os: linux
sudo: required
dist: trusty
language: c
compiler:
  - gcc

branches:
  only:
    - master
    - coverity

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "QCSTWF5FdxycapZ3JmhS/k/z/SXUsJv6BD+pgGkGNsq/MhYT2k8hxLpHzL7Js9gaTFTST/fXinSQA+YCDYJWEZ5vcWYmOCm7j3dUwKxr+FExRptB8rsgpO593CPbLBndju6GN+v+4mTH+CHUlgbPkv4ylFtZrujMffbpBv2YOmo/5TaSsJcC46cXAZAjqEa608aA63FHMZNmPLyMC8ObVysOM7e8eutu+LY4bQBcVUC74y3vgqUTSbyYwZEFw80G9WWSEbffvjc6+N8Nhd6BrTgnPuoev6v3pBjANZyMKFj5dMpsHKAPqSDWETthcfGJGGzsDzs0oCHcI1+4Cew1zq5HGPzNZf45TM9rpnirEHZV+E6PeXajIIad6K85EbFF0QW4zqir4KBhRmW6i7hpkvEZQmaAj66PwOD6Mw2aZlSg6lS5PzNVlNtk2bwVWicSdku7eBc3cG1eaR7NTghAdEJm8LkjyzO/U+RNrOOMUWUNTay8OZO7mIaoNmy21MGyjQGDEnMi5oCLtnfo6Bz4UEaw6bjLhO+qbGya4chyoUIItEVzl/QD1+j2aaJyPG0Wxhi92PeFb0V1gA5MBjkrYCzYz4HfwyvjDhL9zYorvUCrSVNrKYUrOd/J/pSDpF46qtv6v+POvgvQucNHJd4S/0SNKk3LYxYOPOCRfaJjbXQ="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++
      - autoconf
      - pkg-config
      - make
      - automake
      - libxml2-dev
      - libxml2
  coverity_scan:
    project:
      name: "CESNET/Nemea-Detectors"
      description: "Build submitted via Travis CI"
    notification_email: cejkat@cesnet.cz
    build_command_prepend: "./bootstrap.sh && ./configure -q && make clean"
    build_command:   "make -j5"
    branch_pattern: coverity

before_install:
   - pyenv global 2.7.13 3.5.3
   - pip install ply
   - ( git clone --depth 2 https://github.com/CESNET/Nemea-Framework; cd Nemea-Framework; ./bootstrap.sh && ./configure -q --prefix=/usr --bindir=/usr/bin/nemea && make -j10 && sudo make install; (cd pytrap && $(pyenv which python) setup.py install;); (cd pycommon && $(pyenv which python) setup.py install;); )

script:
  - ./bootstrap.sh && ./configure --disable-repobuild && make distcheck
  - mkdir dist-pkgs && cp *.spec *.tar.gz dist-pkgs && (cd dist-pkgs/"$d"; tar --strip-components=1 -xf *.tar.gz;)

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist-pkgs
  github_token: $GITHUB_TOKEN
  target_branch: dist-packages
  on:
    branch: master

